"""Init ecommerce product

Revision ID: 1c90bec2c344
Revises: ec8e5ea96746
Create Date: 2018-04-28 03:11:41.444914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c90bec2c344'
down_revision = 'ec8e5ea96746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_collections',
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=True),
    sa.Column('is_shipping_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_products_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_product_types_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('product_attributes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_attributes_id'], ['product_products_attributes.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_products',
    sa.Column('seo_title', sa.String(length=70), nullable=True),
    sa.Column('seo_description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_product_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_products_attributechoicevalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_products_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price_override', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_allocated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('product_products_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_products_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['product_collections.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_product_types_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('product_variants_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_product_types.id'], ),
    sa.ForeignKeyConstraint(['product_variants_id'], ['product_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_product_types_variants')
    op.drop_table('product_products_collections')
    op.drop_table('product_products_categories')
    op.drop_table('product_product_variants')
    op.drop_table('product_products_attributechoicevalue')
    op.drop_table('product_products')
    op.drop_table('product_product_types_attributes')
    op.drop_table('product_products_attributes')
    op.drop_table('product_product_types')
    op.drop_table('product_collections')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
