"""add ondelete for fks

Revision ID: 26f6012f408f
Revises: 1c90bec2c344
Create Date: 2018-05-06 02:19:27.856829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26f6012f408f'
down_revision = '1c90bec2c344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_products_categories')
    op.drop_constraint('blog_comments_parent_comment_id_fkey', 'blog_comments', type_='foreignkey')
    op.drop_constraint('blog_comments_user_id_fkey', 'blog_comments', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comments', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_comments', 'blog_comments', ['parent_comment_id'], ['id'], ondelete='SET NULL')
    op.add_column('blog_posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('blog_posts_category_id_fkey', 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'blog_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_posts', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('product_product_variants', 'images')
    op.add_column('product_products', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_products', 'images')
    op.add_column('product_product_variants', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key('blog_posts_category_id_fkey', 'blog_posts', 'blog_categories', ['category_id'], ['id'])
    op.drop_column('blog_posts', 'user_id')
    op.drop_constraint(None, 'blog_comments', type_='foreignkey')
    op.drop_constraint(None, 'blog_comments', type_='foreignkey')
    op.create_foreign_key('blog_comments_user_id_fkey', 'blog_comments', 'auth_users', ['user_id'], ['id'])
    op.create_foreign_key('blog_comments_parent_comment_id_fkey', 'blog_comments', 'blog_comments', ['parent_comment_id'], ['id'])
    op.create_table('product_products_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name='product_products_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product_products.id'], name='product_products_categories_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_products_categories_pkey')
    )
    # ### end Alembic commands ###
