"""Add seo post category

Revision ID: ec8e5ea96746
Revises: 494be4d6a723
Create Date: 2018-04-28 03:10:29.565989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8e5ea96746'
down_revision = '494be4d6a723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_categories', sa.Column('seo_description', sa.String(length=300), nullable=True))
    op.add_column('blog_categories', sa.Column('seo_title', sa.String(length=70), nullable=True))
    op.add_column('blog_posts', sa.Column('seo_description', sa.String(length=300), nullable=True))
    op.add_column('blog_posts', sa.Column('seo_title', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'seo_title')
    op.drop_column('blog_posts', 'seo_description')
    op.drop_column('blog_categories', 'seo_title')
    op.drop_column('blog_categories', 'seo_description')
    # ### end Alembic commands ###
